### ISSUE TITLE
Converter class not found

### ISSUE THREAD

**Issue by nklose** [realityforge/geolatte-geom-eclipselink#1]
Hi there, I'm trying to integrate your PostgisConverter into my EclipseLink project but am having trouble getting it working. I have the annotation `@Convert(converter=PostgisConverter.class) ` attached to my geospatial attribute and my `persistence.xml` file looks something like this:

```
<persistence-unit name="myPersistenceUnit">
  <class>org.realityforge.jeo.geolatte.jpa.eclipselink.PostgisConverter</class>
  <properties>
  <property name="eclipselink.session-event-listener" 
    value="org.realityforge.jpa.eclipselink.GeolatteExtension"/>
  </properties>
</persistence-unit>
```

However when I run the project I get this error:
```
Exception [EclipseLink-7351] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd):
org.eclipse.persistence.exceptions.ValidationException
Exception Description: The converter class [org.realityforge.jeo.geolatte.jpa.eclipselink.PostgisConverter]
specified on the mapping attribute [location] from the class [org.mypackage.MyModel] was not found. 
Please ensure the converter class name is correct and exists with the persistence unit definition.
```

Can you advise?

**Comment by realityforge** [comment]
That version of eclipselink is later than the one that this library was developed against (which was 2.3ish and JPA 2.0 IIRC). However you should be able to use the https://github.com/realityforge/geolatte-geom-jpa library which should support your version of eclipselink. (In fact it should support any JPA 2.1 provider)
